# Generated by Django 5.0.1 on 2024-05-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('birthday', models.TextField()),
                ('gender', models.TextField()),
                ('address', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
